import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const notosans = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ['100', '400', '700', '900'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notosans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
